### ISSUE TITLE
Don't instantiate unneeded instances of PerlinNoise.

### ISSUE THREAD

**Issue by peterhenryd** [kakaragame/KVanilla#4]
Instead of instantiating PerlinNoise on each chunk generation. Instantiate it with the construction of world generators since it's completely reusable. You may also want to remove the seed parameter from generation methods. This will also mean that chunk generators cannot be singleton values, and therefore not directly put in the world generation manager. As for alternatives, reflection, you guys can figure that out.

**Comment by ryandw11** [comment]
Thanks for the suggestion, we will be having one instance of PerlinNoise; however, right now I just want to get the game to actually open again. So for now it will stay like that until the game will actually launch.
